# Generated by Django 2.0.5 on 2018-05-23 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titutolo', models.CharField(max_length=30)),
                ('descricao', models.CharField(max_length=500)),
                ('img', models.ImageField(upload_to='img_blog')),
                ('data_blog', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
